# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

superhero = Genre.create(name: "Super Hero")

superhero.titles << captain_marvel_adventures = Title.create(name: "Captain Marvel Adventures")

captain_marvel_adventures.issues << cma_five = Issue.create(number: 5, cover: "http://furycomics.com/Captain_Marvel_Adventures/005/i/Comic_Book_Cover_For_Captain_Marvel_Adventures_Issue_5.jpg")

cma_five.pages << cma_p_one = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/Comic_Book_Cover_For_Captain_Marvel_Adventures_Issue_5.jpg")
cma_five.pages << cma_p_two = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/0.jpg")
cma_five.pages << cma_p_three = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/1.jpg")
cma_five.pages << cma_p_four = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/2.jpg")
cma_five.pages << cma_p_five = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/3.jpg")
cma_five.pages << cma_p_six = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/4.jpg")
cma_five.pages << cma_p_seven = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/5.jpg")
cma_five.pages << cma_p_eight = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/6.jpg")
cma_five.pages << cma_p_nine = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/7.jpg")
cma_five.pages << cma_p_ten = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/8.jpg")
cma_five.pages << cma_p_eleven = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/9.jpg")
cma_five.pages << cma_p_twelve = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/10.jpg")
cma_five.pages << cma_p_thirteen = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/11.jpg")
cma_five.pages << cma_p_fourteen = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/12.jpg")
cma_five.pages << cma_p_fifteen = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/13.jpg")
cma_five.pages << cma_p_sixteen = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/14.jpg")
cma_five.pages << cma_p_seventeen = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/15.jpg")
cma_five.pages << cma_p_eighteen = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/16.jpg")
cma_five.pages << cma_p_nineteen = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/17.jpg")
cma_five.pages << cma_p_twenty = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/18.jpg")
cma_five.pages << cma_p_twentyone = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/19.jpg")
cma_five.pages << cma_p_twentytwo = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/20.jpg")
cma_five.pages << cma_p_twentythree = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/21.jpg")
cma_five.pages << cma_p_twentyfour = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/22.jpg")
cma_five.pages << cma_p_twentyfive = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/23.jpg")
cma_five.pages << cma_p_twentysix = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/24.jpg")
cma_five.pages << cma_p_twentyseven = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/25.jpg")
cma_five.pages << cma_p_twentyeight = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/26.jpg")
cma_five.pages << cma_p_twentynine = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/27.jpg")
cma_five.pages << cma_p_thirty = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/28.jpg")
cma_five.pages << cma_p_thirtyone = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/29.jpg")
cma_five.pages << cma_p_thirtytwo = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/30.jpg")
cma_five.pages << cma_p_thirtythree = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/31.jpg")
cma_five.pages << cma_p_thirtyfour = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/32.jpg")
cma_five.pages << cma_p_thirtyfive = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/33.jpg")
cma_five.pages << cma_p_thirtysix = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/34.jpg")
cma_five.pages << cma_p_thirtyseven = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/35.jpg")
cma_five.pages << cma_p_thirtyeight = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/36.jpg")
cma_five.pages << cma_p_thirtynine = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/37.jpg")
cma_five.pages << cma_p_forty = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/38.jpg")
cma_five.pages << cma_p_fortyone = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/39.jpg")
cma_five.pages << cma_p_fortytwo = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/40.jpg")
cma_five.pages << cma_p_fortythree = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/41.jpg")
cma_five.pages << cma_p_fortyfour = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/42.jpg")
cma_five.pages << cma_p_fortyfive = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/43.jpg")
cma_five.pages << cma_p_fortysix = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/44.jpg")
cma_five.pages << cma_p_fortyseven = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/45.jpg")
cma_five.pages << cma_p_fortyeight = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/46.jpg")
cma_five.pages << cma_p_fortynine = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/47.jpg")
cma_five.pages << cma_p_fifty = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/48.jpg")
cma_five.pages << cma_p_fiftyone = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/49.jpg")
cma_five.pages << cma_p_fiftytwo = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/50.jpg")
cma_five.pages << cma_p_fiftythree = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/52.jpg")
cma_five.pages << cma_p_fiftyfour = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/53.jpg")
cma_five.pages << cma_p_fiftyfive = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/54.jpg")
cma_five.pages << cma_p_fiftysix = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/55.jpg")
cma_five.pages << cma_p_fiftyseven = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/56.jpg")
cma_five.pages << cma_p_fiftyeight = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/57.jpg")
cma_five.pages << cma_p_fiftynine = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/58.jpg")
cma_five.pages << cma_p_sixty = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/59.jpg")
cma_five.pages << cma_p_sixtyone = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/60.jpg")
cma_five.pages << cma_p_sixtytwo = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/61.jpg")
cma_five.pages << cma_p_sixtythree = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/62.jpg")
cma_five.pages << cma_p_sixtyfour = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/63.jpg")
cma_five.pages << cma_p_sixtyfive = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/64.jpg")
cma_five.pages << cma_p_sixtysix = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/65.jpg")
cma_five.pages << cma_p_sixtyseven = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/66.jpg")
cma_five.pages << cma_p_sixtyeight = Page.create(image: "http://furycomics.com/Captain_Marvel_Adventures/005/i/67.jpg")
